"""Vendor Pillow into src/vendor/ so the plugin ships its own high-quality
image resampler (LANCZOS) — the user installs nothing.

Cinema 4D 2024 embeds CPython 3.11, 64-bit Windows, so the wheel we fetch must
be exactly cp311 / win_amd64 — NOT whatever interpreter runs this script. That
is why this uses pip's cross-download flags instead of a plain `pip install`.

    python tools/vendor_pillow.py

Re-run it to refresh; the plugin works without it (Cinema's own bitmap engine
is the fallback), it just resizes with lower quality and refuses alpha maps.
"""
from __future__ import annotations

import argparse
import pathlib
import shutil
import subprocess
import sys
import tempfile
import zipfile

# The interpreter Cinema 4D 2024 embeds. Bump these when C4D bumps Python.
PY_VERSION = "311"
PLATFORM = "win_amd64"
PILLOW = "pillow==11.3.0"

ROOT = pathlib.Path(__file__).resolve().parent.parent
VENDOR = ROOT / "src" / "vendor"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--package", default=PILLOW)
    args = ap.parse_args()

    with tempfile.TemporaryDirectory() as tmp:
        cmd = [
            sys.executable, "-m", "pip", "download", args.package,
            "--only-binary=:all:",
            "--implementation", "cp",
            "--python-version", PY_VERSION,
            "--abi", "cp" + PY_VERSION,
            "--platform", PLATFORM,
            "--no-deps",
            "-d", tmp,
        ]
        print(" ".join(cmd))
        if subprocess.call(cmd) != 0:
            print("pip download failed", file=sys.stderr)
            return 1

        wheels = list(pathlib.Path(tmp).glob("*.whl"))
        if not wheels:
            print("no wheel downloaded", file=sys.stderr)
            return 1

        if VENDOR.exists():
            shutil.rmtree(VENDOR)
        VENDOR.mkdir(parents=True)
        for wheel in wheels:
            print("unpacking %s" % wheel.name)
            with zipfile.ZipFile(wheel) as zf:
                zf.extractall(VENDOR)

    (VENDOR / "README.md").write_text(
        "Vendored third-party packages, unpacked from the official wheels for\n"
        "CPython %s / %s (the interpreter Cinema 4D 2024 embeds).\n\n"
        "Generated by tools/vendor_pillow.py — do not edit by hand.\n\n"
        "Pillow is distributed under the MIT-CMU license; its LICENSE file is\n"
        "kept in the .dist-info folder next to this file.\n" % (PY_VERSION, PLATFORM),
        encoding="utf-8")
    print("vendored into %s" % VENDOR)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
